/** --------------------------------------------------------------------------------------------------------------------
 * @file productContent.data.ts
 * @fileOverview editorial content for the seven product pages, extracted from
 *               ZX_DEFAULT_PRODUCT_CONTENT in ../ZexServerAdditionalPages/site-data.js.
 *
 * @note Generated by executing the reference file against a stub `window` and serialising the
 *       result - not transcribed by hand. Re-generate rather than edit.
 *
 *       The reference repeated each city's flag and country inside every product's content; here
 *       only `locationCities` is stored and the service joins to the location table.
 */
import { ProductContentNamespace } from '@src/app/productContent/namespace/productContent.namespace';

export const PRODUCT_CONTENT_SEED_DATA: Array<Partial<ProductContentNamespace.IProductContent>> = [
  {
    product: 'VPS Hosting',
    heroBadge: 'KVM VPS HOSTING',
    heroHeading1: 'High-Performance',
    heroHeadingAccent: 'VPS Hosting',
    heroImage: '',
    heroSubheading: 'Powerful KVM VPS with NVMe storage, dedicated resources and high-speed global networks.',
    ctaHeading: 'Ready to Deploy Your VPS?',
    ctaSubheading: 'Powerful infrastructure. Simple pricing. No unnecessary complexity.',
    featureStrip: [
      { icon: '🖥️', title: 'KVM Virtualization', subtitle: 'Enterprise Grade' },
      { icon: '⚡', title: 'NVMe SSD', subtitle: 'Ultra Fast Storage' },
      { icon: '🛡️', title: '99.9% Uptime', subtitle: 'Network Guarantee' },
      { icon: '🌐', title: '1Gbps+ Network', subtitle: 'High Speed Connection' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Expert Assistance' },
    ],
    whyChoose: [
      { icon: '⚡', title: 'High Performance', subtitle: 'Powerful CPUs & NVMe' },
      { icon: '🖥️', title: 'Dedicated Resources', subtitle: 'KVM virtualization' },
      { icon: '🔒', title: 'Secure Infrastructure', subtitle: 'Advanced DDoS protection' },
      { icon: '🌍', title: 'Global Locations', subtitle: 'Deploy closer to users' },
      { icon: '📈', title: 'Easy Scaling', subtitle: 'Upgrade in seconds' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Real experts, always here' },
    ],
    faq: [
      {
        question: 'What is a KVM VPS?',
        answer:
          'A VPS virtualized with KVM, giving you dedicated CPU, RAM and storage allocations independent of other tenants.',
      },
      {
        question: 'Do I get full root access?',
        answer: 'Yes, every VPS plan includes full root access for complete control.',
      },
      {
        question: 'Can I upgrade my VPS anytime?',
        answer: 'Yes, resources can be scaled up in a few clicks with no downtime migration needed for most upgrades.',
      },
      {
        question: 'How quickly is my VPS deployed?',
        answer: 'Most VPS instances are deployed within 60 seconds of checkout.',
      },
      {
        question: 'Which operating systems are available?',
        answer: 'Ubuntu, Debian, AlmaLinux, Rocky Linux and Windows Server, with more templates available on request.',
      },
      {
        question: 'Do you offer backups for VPS?',
        answer: 'Backup add-ons are available on all VPS plans — contact support to enable one.',
      },
    ],
    gridOneTitle: 'Choose Your Operating System',
    gridOneSubtitle: 'Deploy your preferred OS in minutes.',
    gridOne: [
      { icon: '🐧', label: 'Ubuntu' },
      { icon: '🌪️', label: 'Debian' },
      { icon: '🍋', label: 'AlmaLinux' },
      { icon: '🪨', label: 'Rocky Linux' },
      { icon: '🪟', label: 'Windows Server' },
    ],
    gridTwoTitle: 'Deploy More Than a Server',
    gridTwoSubtitle: 'One-click install popular control panels and applications.',
    gridTwo: [
      { icon: '🔑', label: 'cPanel' },
      { icon: '💾', label: 'DirectAdmin' },
      { icon: '🔧', label: 'Plesk' },
      { icon: '📦', label: 'Docker' },
      { icon: '🐸', label: 'WordPress' },
    ],
    includedFeatures: [
      { label: 'Full Root Access' },
      { label: 'KVM Virtualisation' },
      { label: 'DDoS Protection' },
      { label: '99.9% Uptime SLA' },
      { label: '24/7 Expert Support' },
      { label: 'Free Setup' },
    ],
    locationCities: ['Frankfurt', 'Amsterdam', 'New York', 'Helsinki', 'London'],
  },
  {
    product: 'Windows VPS',
    heroBadge: 'WINDOWS VPS HOSTING',
    heroHeading1: 'Powerful Windows Servers,',
    heroHeadingAccent: 'Ready in Minutes',
    heroImage: '',
    heroSubheading:
      'Run your applications, desktop and business workflows on high-performance Windows VPS with maximum compatibility.',
    ctaHeading: 'Ready to Deploy Your Windows VPS?',
    ctaSubheading: 'Powerful infrastructure. Simple pricing. No unnecessary complexity.',
    featureStrip: [
      { icon: '🪟', title: 'Licensed Windows Server', subtitle: 'Included, No Extra Fees' },
      { icon: '🖥️', title: 'Full RDP Access', subtitle: 'Desktop & Admin Console' },
      { icon: '⚡', title: 'NVMe SSD', subtitle: 'Ultra Fast Storage' },
      { icon: '🛡️', title: '99.9% Uptime', subtitle: 'Network Guarantee' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Expert Assistance' },
    ],
    whyChoose: [
      { icon: '🪟', title: 'Genuine Windows License', subtitle: 'No extra activation steps' },
      { icon: '🖥️', title: 'Full Desktop Access', subtitle: 'RDP from anywhere' },
      { icon: '⚡', title: 'High Performance', subtitle: 'NVMe-backed compute' },
    ],
    faq: [
      {
        question: 'Does the price include a Windows license?',
        answer: 'Yes, a genuine Windows Server license is included on every plan at no extra cost.',
      },
      {
        question: 'How do I connect to my Windows VPS?',
        answer: 'You connect over Remote Desktop Protocol (RDP) using the credentials provided after deployment.',
      },
      {
        question: 'Can I run business software like SQL Server?',
        answer: 'Yes, you have full admin access to install SQL Server, IIS or any Windows-compatible software.',
      },
      {
        question: 'How fast is deployment?',
        answer: 'Most Windows VPS instances are ready within a few minutes of checkout.',
      },
    ],
    gridOneTitle: 'Included Software',
    gridOneSubtitle: 'Ready to use the moment your server deploys.',
    gridOne: [
      { icon: '🖥️', label: 'RDP Access' },
      { icon: '🌐', label: 'IIS' },
      { icon: '🧱', label: '.NET Framework' },
      { icon: '🗄️', label: 'SQL Server Express' },
      { icon: '⚙️', label: 'Windows Admin Center' },
    ],
    gridTwoTitle: 'Popular Add-ons',
    gridTwoSubtitle: 'One-click install additional tools.',
    gridTwo: [
      { icon: '🔧', label: 'Plesk' },
      { icon: '📊', label: 'WHMCS' },
      { icon: '🖥️', label: 'Remote Tools' },
    ],
    includedFeatures: [
      { label: 'Full Administrator Access' },
      { label: 'Remote Desktop (RDP) Access' },
      { label: 'Windows Server License Included' },
      { label: 'DDoS Protection' },
      { label: '99.9% Uptime SLA' },
      { label: '24/7 Expert Support' },
    ],
    locationCities: ['Frankfurt', 'Amsterdam', 'New York', 'London'],
  },
  {
    product: 'Trading VPS',
    heroBadge: 'TRADING VPS',
    heroHeading1: 'Ultra-Low Latency',
    heroHeadingAccent: 'Trading VPS Built for Traders.',
    heroImage: '',
    heroSubheading:
      'Run your trading platforms and Expert Advisors 24/7 with a fast, stable and low-latency VPS infrastructure.',
    ctaHeading: 'Ready to Deploy Your Trading VPS?',
    ctaSubheading: 'Low latency. Maximum uptime. Built for serious traders.',
    featureStrip: [
      { icon: '⚡', title: 'Ultra-Low Latency', subtitle: 'Sub-Millisecond Execution' },
      { icon: '📈', title: '99.99% Uptime', subtitle: 'Never Miss a Trade' },
      { icon: '🖥️', title: 'NVMe Storage', subtitle: 'Fast Platform Loading' },
      { icon: '🎯', title: 'Dedicated Resources', subtitle: 'No Shared CPU' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Expert Assistance' },
    ],
    whyChoose: [
      { icon: '⚡', title: 'Ultra-Low Latency to Brokers', subtitle: 'Placed near major exchanges' },
      { icon: '📈', title: '24/7 Uptime for EAs', subtitle: 'Your bots never stop running' },
      { icon: '🖥️', title: 'NVMe-Backed Execution', subtitle: 'Fast order placement' },
      { icon: '🎯', title: 'Dedicated Trading Resources', subtitle: 'No noisy-neighbor slowdowns' },
    ],
    faq: [
      {
        question: 'How low is the latency to brokers?',
        answer:
          'Latency depends on location, but our trading-optimized network typically achieves sub-millisecond to single-digit millisecond pings to major brokers.',
      },
      {
        question: 'Can I run MetaTrader and Expert Advisors 24/7?',
        answer:
          'Yes, your Trading VPS runs continuously so your platforms and EAs keep trading even when your computer is off.',
      },
      {
        question: 'Which trading platforms are supported?',
        answer: 'MetaTrader 4, MetaTrader 5, cTrader, NinjaTrader and TradingView all run natively on Trading VPS.',
      },
      {
        question: 'Can I choose a location near my broker?',
        answer: 'Yes, pick the datacenter closest to your broker’s servers to minimize latency.',
      },
    ],
    gridOneTitle: 'Optimized for Trading Platforms',
    gridOneSubtitle: 'Pre-configured for the platforms traders use most.',
    gridOne: [
      { icon: '📊', label: 'MetaTrader 4' },
      { icon: '📈', label: 'MetaTrader 5' },
      { icon: '📉', label: 'cTrader' },
      { icon: '💻', label: 'NinjaTrader' },
      { icon: '🖥️', label: 'TradingView' },
    ],
    gridTwoTitle: 'Designed for Traders. Built for Performance.',
    gridTwoSubtitle: '',
    gridTwo: [
      { icon: '⚡', label: 'Sub-ms Execution' },
      { icon: '📈', label: '99.99% Uptime' },
      { icon: '🖥️', label: 'NVMe Storage' },
      { icon: '🎯', label: 'Dedicated CPU' },
      { icon: '👀', label: '24/7 Monitoring' },
    ],
    includedFeatures: [
      { label: 'Ultra-low Latency to Brokers' },
      { label: 'MT4 / MT5 Ready' },
      { label: 'Dedicated Resources' },
      { label: 'DDoS Protection' },
      { label: '99.9% Uptime SLA' },
      { label: '24/7 Expert Support' },
    ],
    locationCities: ['New York', 'London', 'Frankfurt', 'Tokyo'],
  },
  {
    product: 'Dedicated Servers',
    heroBadge: 'BARE METAL SERVERS',
    heroHeading1: 'Your Server.',
    heroHeadingAccent: '100% Your Hardware.',
    heroImage: '',
    heroSubheading:
      'Run your most demanding workloads on dedicated, bare-metal hardware. No virtualization, no shared resources.',
    ctaHeading: 'Ready to Deploy Your Dedicated Server?',
    ctaSubheading: 'Enterprise-grade hardware, provisioned within 24 hours.',
    featureStrip: [
      { icon: '🖥️', title: 'Full Hardware Control', subtitle: 'No Virtualization' },
      { icon: '🏗️', title: 'Enterprise Components', subtitle: 'Xeon & EPYC Options' },
      { icon: '🌐', title: '10Gbps+ Network', subtitle: 'High Speed Connection' },
      { icon: '🛡️', title: '99.9% Uptime', subtitle: 'Network Guarantee' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Expert Assistance' },
    ],
    whyChoose: [
      { icon: '🖥️', title: 'Full Hardware Control', subtitle: 'Nothing shared with other tenants' },
      { icon: '⚡', title: 'Higher Raw Performance', subtitle: 'No virtualization overhead' },
      { icon: '🔇', title: 'No Noisy Neighbors', subtitle: 'Consistent, predictable performance' },
      { icon: '⚙️', title: 'Custom Configurations', subtitle: 'Built to your specification' },
    ],
    faq: [
      {
        question: 'How is a dedicated server different from a VPS?',
        answer:
          'A dedicated server gives you an entire physical machine with no virtualization or shared resources, for maximum raw performance.',
      },
      {
        question: 'How long does provisioning take?',
        answer: 'Most dedicated servers are provisioned and ready within 24 hours of order.',
      },
      {
        question: 'Can I customize the hardware configuration?',
        answer: 'Yes, contact our sales team for custom CPU, RAM, storage and network configurations.',
      },
      {
        question: 'Do you offer IPMI/KVM access?',
        answer:
          'Yes, out-of-band IPMI access is included so you can manage your server even if the OS is unresponsive.',
      },
    ],
    gridOneTitle: 'Included Features',
    gridOneSubtitle: 'Every dedicated server ships with these as standard.',
    gridOne: [
      { icon: '🗄️', label: 'RAID Storage' },
      { icon: '🖥️', label: 'IPMI / KVM Access' },
      { icon: '🛡️', label: 'DDoS Protection' },
      { icon: '💿', label: 'Custom OS Install' },
      { icon: '🌐', label: '10Gbps Network' },
    ],
    gridTwoTitle: 'Popular Configurations',
    gridTwoSubtitle: 'Common builds, or fully custom on request.',
    gridTwo: [
      { icon: '🖥️', label: 'Single Xeon' },
      { icon: '🖥️', label: 'Dual Xeon' },
      { icon: '⚡', label: 'AMD EPYC' },
      { icon: '🗄️', label: 'Storage Server' },
      { icon: '🎮', label: 'GPU Server' },
    ],
    includedFeatures: [
      { label: 'IPMI / KVM Access' },
      { label: 'Hardware Replacement SLA' },
      { label: 'DDoS Protection' },
      { label: '99.9% Uptime SLA' },
      { label: '24/7 Expert Support' },
      { label: 'Free Setup' },
    ],
    locationCities: ['Frankfurt', 'Amsterdam', 'New York', 'Helsinki', 'London'],
  },
  {
    product: 'Web Hosting',
    heroBadge: 'WEB HOSTING',
    heroHeading1: 'Fast, Secure Web Hosting',
    heroHeadingAccent: 'for Your Website.',
    heroImage: '',
    heroSubheading: 'Reliable NVMe web hosting with everything you need to launch, grow and manage your website.',
    ctaHeading: 'Ready to Launch Your Website?',
    ctaSubheading: 'Get reliable, fast and secure web hosting for your business today.',
    featureStrip: [
      { icon: '⚡', title: 'NVMe SSD', subtitle: 'Ultra Fast Storage' },
      { icon: '🛡️', title: '99.9% Uptime', subtitle: 'Network Guarantee' },
      { icon: '📦', title: 'Free Migration', subtitle: 'We Move Your Site' },
      { icon: '🐸', title: '1-Click WordPress', subtitle: 'Install in Minutes' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Expert Assistance' },
    ],
    whyChoose: [
      { icon: '🔒', title: 'Free SSL', subtitle: 'Every domain, every plan' },
      { icon: '💾', title: 'Daily Backups', subtitle: 'Restore anytime' },
      { icon: '⚡', title: 'One-Click Apps', subtitle: 'WordPress and more' },
      { icon: '🌐', title: 'Unmetered Bandwidth', subtitle: 'No surprise overage fees' },
      { icon: '📦', title: 'Free Migration', subtitle: 'We move your site for you' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Real experts, always here' },
    ],
    faq: [
      {
        question: 'Is an SSL certificate included?',
        answer: 'Yes, every plan includes a free SSL certificate for all your domains.',
      },
      {
        question: 'Do you offer website migration?',
        answer: 'Yes, our team will migrate your website from your current host for free.',
      },
      {
        question: 'Can I host WordPress websites?',
        answer: 'Yes, WordPress can be installed in one click on any plan, with dedicated tools on WordPress Hosting.',
      },
      {
        question: 'Which control panel is included?',
        answer: 'All plans include a full-featured control panel for managing sites, email, domains and databases.',
      },
      {
        question: 'How many websites can I host?',
        answer: 'Depends on your plan, from 1 website on the starter tier to unlimited on higher tiers.',
      },
      {
        question: 'Can I upgrade my hosting plan later?',
        answer: 'Yes, you can upgrade to a higher plan anytime from your dashboard with no downtime.',
      },
    ],
    gridOneTitle: 'Full-Featured Control Panel',
    gridOneSubtitle: 'Manage everything from one dashboard.',
    gridOne: [
      { icon: '🔑', label: 'cPanel' },
      { icon: '⚙️', label: 'Softaculous' },
      { icon: '🗄️', label: 'phpMyAdmin' },
      { icon: '⏰', label: 'Cron Jobs' },
      { icon: '💻', label: 'SSH Access' },
    ],
    gridTwoTitle: 'Included With Every Plan',
    gridTwoSubtitle: '',
    gridTwo: [
      { icon: '🔒', label: 'Free SSL' },
      { icon: '📦', label: 'Free Migration' },
      { icon: '💾', label: 'Daily Backups' },
      { icon: '🛡️', label: '99.9% Uptime' },
      { icon: '🎧', label: '24/7 Support' },
    ],
    includedFeatures: [
      { label: 'LiteSpeed Web Server' },
      { label: 'HTML, PHP Support' },
      { label: 'Unlimited Bandwidth' },
      { label: 'Unlimited Parked Domains' },
      { label: 'Laravel Support' },
      { label: 'Free SSL Certificate' },
    ],
    locationCities: ['Frankfurt', 'Amsterdam', 'New York', 'Helsinki', 'London'],
  },
  {
    product: 'WordPress Hosting',
    heroBadge: 'WORDPRESS HOSTING',
    heroHeading1: 'Managed WordPress Hosting',
    heroHeadingAccent: 'Built for Speed.',
    heroImage: '',
    heroSubheading: 'Optimized WordPress hosting with 1-click install, automatic updates and built-in caching.',
    ctaHeading: 'Ready to Launch Your WordPress Site?',
    ctaSubheading: 'Get managed, fast and secure WordPress hosting today.',
    featureStrip: [
      { icon: '🚀', title: '1-Click Install', subtitle: 'WordPress in Minutes' },
      { icon: '⚡', title: 'NVMe SSD', subtitle: 'Ultra Fast Storage' },
      { icon: '🛡️', title: '99.9% Uptime', subtitle: 'Network Guarantee' },
      { icon: '🔄', title: 'Auto Updates', subtitle: 'Core, Themes & Plugins' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Expert Assistance' },
    ],
    whyChoose: [
      { icon: '🔄', title: 'Automatic Updates', subtitle: 'Core, plugins & themes' },
      { icon: '⚡', title: 'Built-in Caching', subtitle: 'Server-level speed boost' },
      { icon: '🔒', title: 'Free SSL', subtitle: 'Every site, every plan' },
      { icon: '🧪', title: 'Staging Environment', subtitle: 'Test changes safely' },
      { icon: '📦', title: 'Free Migration', subtitle: 'We move your site for you' },
      { icon: '🎧', title: '24/7 Support', subtitle: 'Real experts, always here' },
    ],
    faq: [
      {
        question: 'Is WordPress pre-installed?',
        answer: 'Yes, every plan comes with 1-click WordPress install, or we can pre-install it for you.',
      },
      {
        question: 'Do you offer WordPress migration?',
        answer: 'Yes, our team will migrate your WordPress site from your current host for free.',
      },
      {
        question: 'Are plugin and theme updates automatic?',
        answer: 'Core, plugin and theme updates run automatically, with staging to test changes safely first.',
      },
      {
        question: 'Is caching included?',
        answer: 'Yes, built-in server-level caching is enabled on every plan for faster page loads.',
      },
      {
        question: 'How many WordPress sites can I host?',
        answer: 'Depends on your plan, from 1 site on Starter to unlimited on Agency.',
      },
      {
        question: 'Can I upgrade my plan later?',
        answer: 'Yes, you can upgrade to a higher plan anytime from your dashboard with no downtime.',
      },
    ],
    gridOneTitle: 'Included Tools',
    gridOneSubtitle: 'Everything a WordPress site needs.',
    gridOne: [
      { icon: '⚙️', label: 'WP-CLI' },
      { icon: '🧪', label: 'Staging' },
      { icon: '⚡', label: 'Caching' },
      { icon: '💻', label: 'SFTP / SSH' },
      { icon: '🗄️', label: 'phpMyAdmin' },
    ],
    gridTwoTitle: 'Popular Plugins Supported',
    gridTwoSubtitle: '',
    gridTwo: [
      { icon: '🛒', label: 'WooCommerce' },
      { icon: '🎨', label: 'Elementor' },
      { icon: '🔍', label: 'Yoast SEO' },
      { icon: '🚀', label: 'WP Rocket' },
      { icon: '✉️', label: 'Contact Form 7' },
    ],
    includedFeatures: [
      { label: '1-Click WordPress Install' },
      { label: 'Built-in Caching' },
      { label: 'Unlimited Bandwidth' },
      { label: 'Automatic WP Updates' },
      { label: 'Staging Environment' },
      { label: 'Free SSL Certificate' },
    ],
    locationCities: ['Frankfurt', 'Amsterdam', 'New York', 'Helsinki', 'London'],
  },
  {
    product: 'Software Licenses',
    heroBadge: 'SOFTWARE LICENSES',
    heroHeading1: 'Licenses, Installed.',
    heroHeadingAccent: 'Configured. Done.',
    heroImage: '',
    heroSubheading:
      'Genuine control panel and OS licenses for cPanel, Plesk, DirectAdmin, Windows Server and more — with optional install and setup.',
    ctaHeading: 'Ready to Get Licensed?',
    ctaSubheading: 'Pick your software, add installation if you need it.',
    featureStrip: [
      { icon: '✅', title: 'Genuine Licenses', subtitle: 'Direct from the vendor' },
      { icon: '🛠️', title: 'Installation Available', subtitle: 'Done for you, on request' },
      { icon: '⚡', title: 'Fast Activation', subtitle: 'Most licenses same-day' },
      { icon: '🎧', title: '24/7 Expert Support', subtitle: 'Real engineers, always' },
    ],
    whyChoose: [
      { icon: '✅', title: 'Genuine Licenses', subtitle: 'Purchased direct from the vendor' },
      { icon: '🛠️', title: 'Installed by Experts', subtitle: 'Not just a key — a working setup' },
      { icon: '🌐', title: 'Works Everywhere', subtitle: 'On ZexServer or your own hardware' },
      { icon: '⚡', title: 'Fast Activation', subtitle: 'Most licenses ready same-day' },
      { icon: '🔁', title: 'Flexible Billing', subtitle: 'Monthly, change or cancel anytime' },
      { icon: '🎧', title: '24/7 Expert Support', subtitle: 'Real engineers, always on call' },
    ],
    faq: [
      {
        question: 'Are these genuine licenses?',
        answer: 'Yes. All licenses are purchased directly from the software vendor and activated under your account.',
      },
      {
        question: 'Can I use a license on my own server?',
        answer: 'Yes, licenses work on ZexServer infrastructure or any compatible server you already run.',
      },
      {
        question: 'What does "Install License" include?',
        answer:
          'We install the software on your server and confirm it’s running — ready for you or our team to configure.',
      },
      {
        question: 'What does "Configuration" add?',
        answer: 'Initial setup of core settings so the software is production-ready — not just installed, but usable.',
      },
      {
        question: 'Can I switch or cancel a license later?',
        answer: 'Yes, licenses are billed monthly and can be changed or cancelled from your dashboard anytime.',
      },
      {
        question: 'How fast is activation?',
        answer:
          'Most licenses activate same-day. Installation and configuration add-ons are typically completed within 24 hours.',
      },
    ],
    gridOneTitle: 'License Categories',
    gridOneSubtitle: 'Every category we support.',
    gridOne: [
      { icon: '🔑', label: 'cPanel' },
      { icon: '🔧', label: 'Plesk' },
      { icon: '💾', label: 'DirectAdmin' },
      { icon: '🪟', label: 'Windows Server' },
    ],
    gridTwoTitle: 'Support Included',
    gridTwoSubtitle: '',
    gridTwo: [
      { icon: '🛠️', label: 'Installation' },
      { icon: '⚙️', label: 'Configuration' },
      { icon: '🎧', label: '24/7 Support' },
    ],
    includedFeatures: [],
    locationCities: ['Frankfurt', 'Amsterdam', 'New York', 'Helsinki', 'London'],
  },
];
