/** --------------------------------------------------------------------------------------------------------------------
 * @file siteContent.data.ts
 * @fileOverview content for the non-product pages plus the footer, extracted from the reference's
 *               admin dashboard defaultDB (pageHome / pageAbout / pageContact / pageSupport /
 *               pageLegal / footer) in ../ZexServerAdditionalPages/Admin Dashboard.dc.html.
 *
 * @note Generated by evaluating the reference objects, not transcribed. Two deliberate edits:
 *
 *       1. The footer comes from site-data.js's ZX_DEFAULT_FOOTER, NOT from the admin dashboard's
 *          own `footer` object - the reference disagrees with itself here. The admin copy points
 *          Terms of Service and Privacy Policy at '#' and omits WordPress Hosting, while the
 *          version the public pages actually render links them properly. Link targets are remapped
 *          from `.dc.html` filenames onto this app's routes; entries left as '#' stay '#'.
 *
 *       2. Invented marketing metrics: home.reviewScore ('4.8') and home.reviewCount ('1,265') are
 *          seeded EMPTY so the rating line only appears once real figures exist. The About stats
 *          (founded, serversDeployed, uptime) carry the mockup's figures so the strip is complete on
 *          day one - they are admin-editable. about.datacentersCount stays empty: the reference's 5
 *          contradicts its eight locations, which is a good illustration of why these are
 *          decoration rather than data - the About page reads the real count from the stats
 *          endpoint instead.
 */
import { SiteContentNamespace } from '@src/app/siteContent/namespace/siteContent.namespace';

export const SITE_CONTENT_SEED_DATA: Array<Partial<SiteContentNamespace.ISiteContent>> = [
  {
    page: SiteContentNamespace.EPage.HOME,
    content: {
      heroBadge: 'INFRASTRUCTURE THAT SCALES WITH YOU',
      heroHeading: 'Powering Business-Critical Infrastructure.',
      heroImage: '',
      heroSubheading:
        'VPS, Windows VPS, Trading VPS, Dedicated Servers, Web Hosting, Software Licenses and server management — all on reliable, high-performance infrastructure.',
      primaryCta: 'Explore Our Plans',
      secondaryCta: 'Talk to Sales',
      reviewScore: '',
      reviewCount: '',
      bannerTitle: 'Not Sure What You Need?',
      bannerSubtitle: "Talk to our team and we'll recommend the right infrastructure for your workload.",
      bannerCta: 'Talk to Us',
      ctaHeading: 'Ready to Get Started?',
      ctaSubheading: 'Powerful infrastructure. Simple pricing. No unnecessary complexity.',
      ctaPrimaryLabel: 'Explore Our Plans',
      ctaSecondaryLabel: 'Contact Us',
      footerTagline:
        'Powering business-critical infrastructure: VPS, Dedicated Servers, Web Hosting and Software Licenses.',
      features: [
        { title: 'NVMe SSD', subtitle: 'Ultra Fast Storage', icon: 'bars' },
        { title: 'Global Locations', subtitle: 'Multiple Datacenters', icon: 'globe' },
        { title: 'Secure Infrastructure', subtitle: 'DDoS Protected', icon: 'shield' },
        { title: 'Scalable Resources', subtitle: 'Upgrade Anytime', icon: 'server' },
        { title: '24/7 Support', subtitle: 'Expert Assistance', icon: 'headset' },
      ],
      productCards: [
        {
          name: 'VPS Hosting',
          tagline: 'Flexible. Fast. Scalable.',
          description: 'KVM Virtual Servers with NVMe storage and premium network connectivity.',
          price: 5.99,
          ctaLabel: 'Explore VPS',
        },
        {
          name: 'Dedicated Servers',
          tagline: 'Maximum Power. Total Control.',
          description: 'Bare-metal performance for demanding workloads and mission-critical applications.',
          price: 69.99,
          ctaLabel: 'Explore Dedicated',
        },
      ],
      whyChoose: [
        { title: 'High Performance', subtitle: 'Powerful CPUs & NVMe', icon: 'bars' },
        { title: 'Global Infrastructure', subtitle: 'Multiple locations', icon: 'globe' },
        { title: 'Secure Infrastructure', subtitle: 'DDoS protection built-in', icon: 'shield' },
        { title: 'Scalable Resources', subtitle: 'Grow without migrating', icon: 'server' },
        { title: 'Fast Deployment', subtitle: 'Ready in minutes', icon: 'ticket' },
        { title: 'Professional Setup', subtitle: 'Installation & configuration', icon: 'gear' },
        { title: 'Flexible Solutions', subtitle: 'Plans for every workload', icon: 'license' },
        { title: '24/7 Support', subtitle: 'Real experts, always here', icon: 'headset' },
      ],
      testimonials: [
        {
          _id: 'ts_1',
          quote:
            "Migrated our production databases to ZexServer's Dedicated Servers and haven't looked back. Setup was fast and support actually knows what they're doing.",
          name: 'Daniel R.',
          role: 'CTO, SaaS startup',
          rating: 5,
        },
        {
          _id: 'ts_2',
          quote:
            'Running MT4 on their Trading VPS cut my execution latency noticeably. Uptime has been rock solid for over a year.',
          name: 'Amara K.',
          role: 'Independent trader',
          rating: 5,
        },
        {
          _id: 'ts_3',
          quote:
            'We host a dozen client sites on their Web Hosting plans. NVMe speed is noticeable and their support resolves tickets same day.',
          name: 'Priya M.',
          role: 'Agency owner',
          rating: 5,
        },
      ],
    },
  },
  {
    page: SiteContentNamespace.EPage.ABOUT,
    content: {
      heroHeading: 'Infrastructure You Can Depend On.',
      heroImage: '',
      heroSubheading:
        'ZexServer builds and operates the servers, panels and support that businesses run on — so our customers can focus on their own products, not their infrastructure.',
      founded: '2015',
      datacentersCount: '',
      serversDeployed: '12,000+',
      uptime: '99.9%',
      storyHeading: 'Built by engineers who got tired of unreliable hosting.',
      storyParagraph1:
        "ZexServer started as a small team running a handful of VPS nodes for developer friends who needed something more dependable than the budget hosts they'd outgrown.",
      storyParagraph2:
        "Today we operate datacenters across Europe and North America, but the priorities haven't changed: fast NVMe storage, honest pricing, and a support team that answers when something breaks.",
      ctaHeading: 'Want to Work With Us?',
      ctaSubheading: 'Explore our plans or reach out with questions.',
      footerTagline:
        'Powering business-critical infrastructure: VPS, Dedicated Servers, Web Hosting and Software Licenses.',
      values: [
        {
          title: 'Reliability',
          description: "Redundant power, network and hardware, so your uptime doesn't depend on luck.",
          icon: 'shield',
        },
        {
          title: 'Transparency',
          description: 'Clear pricing, real specs and honest answers — no surprise fees or fine print.',
          icon: 'shield',
        },
        {
          title: 'Speed',
          description: 'NVMe storage and premium network paths, because slow infrastructure costs you customers.',
          icon: 'bars',
        },
        {
          title: 'Real Support',
          description: 'Actual engineers on the other end, available 24/7 for critical issues.',
          icon: 'headset',
        },
      ],
    },
  },
  {
    page: SiteContentNamespace.EPage.CONTACT,
    content: {
      heroHeading: "We're Here to Help.",
      heroImage: '',
      heroSubheading:
        'Questions about a plan, a technical issue, or just want to talk infrastructure? Reach out any way that works for you.',
      businessName: 'ZexServer',
      businessWebsite: 'zexserver.com',
      businessAddress: '1201 Infrastructure Ave, Suite 400\nWilmington, DE 19801, USA',
      salesHours: 'Mon–Fri, 9am–7pm CET',
      faqTeaserHeading: 'Still Have Questions?',
      faqTeaserSubheading: 'Each product has its own FAQ with detailed answers.',
      socialLinks: [
        { label: 'X', url: '#', icon: '' },
        { label: 'in', url: '#', icon: '' },
        { label: 'Website', url: '#', icon: 'globe' },
      ],
      channels: [
        { label: 'Email', description: 'Response within a few hours', value: 'support@zexserver.com', icon: 'mail' },
        { label: 'WhatsApp', description: 'Mon–Fri, 9am–7pm CET', value: '+1 (800) 555-0142', icon: 'headset' },
        { label: 'Support Ticket', description: 'Track technical requests', value: 'Open a Ticket', icon: 'ticket' },
      ],
    },
  },
  {
    page: SiteContentNamespace.EPage.SUPPORT,
    content: {
      heroHeading: 'How Can We Help?',
      heroImage: '',
      heroSubheading: 'Browse our knowledge base below, or reach a real engineer any time.',
      kbCategories: [
        { title: 'Getting Started', description: 'First login, server access and initial setup guides.', icon: 'info' },
        { title: 'Billing & Payments', description: 'Invoices, payment methods, renewals and refunds.', icon: 'card' },
        {
          title: 'Server Management',
          description: 'Reboots, resizing, backups and control panel access.',
          icon: 'server',
        },
        { title: 'Security', description: 'Firewalls, DDoS protection, SSL and account security.', icon: 'shield' },
        {
          title: 'Software Licenses',
          description: 'Activation, transfers and installation of licensed software.',
          icon: 'license',
        },
        { title: 'Networking', description: 'IP addresses, DNS, bandwidth and connectivity issues.', icon: 'bars' },
      ],
      faqs: [
        {
          question: 'How fast do you respond to support requests?',
          answer: 'Standard tickets are answered within a few hours. Critical, service-down issues are handled 24/7.',
        },
        {
          question: 'Where can I check for ongoing outages?',
          answer: 'Our network status page lists any active incidents and maintenance windows in real time.',
        },
        {
          question: 'Do you help with server migrations?',
          answer: 'Yes, our team can assist migrating data and configurations from your previous host.',
        },
        {
          question: 'Can I get support for a server I self-manage?',
          answer:
            'We provide infrastructure-level support for all servers. Full OS-level management is available as an add-on.',
        },
        {
          question: 'What information should I include in a ticket?',
          answer: "Your server ID or hostname, a description of the issue, and any error messages you've seen.",
        },
      ],
    },
  },
  {
    page: SiteContentNamespace.EPage.FOOTER,
    content: {
      tagline: 'Powering business-critical infrastructure: VPS, Dedicated Servers, Web Hosting and Software Licenses.',
      copyright: '© 2026 ZexServer. All rights reserved.',
      columns: [
        {
          heading: 'PRODUCTS',
          links: [
            { label: 'VPS Hosting', url: '/vps-hosting' },
            { label: 'Dedicated Servers', url: '/dedicated-servers' },
            { label: 'Trading VPS', url: '/trading-vps' },
            { label: 'Windows VPS', url: '/windows-vps' },
            { label: 'Web Hosting', url: '/web-hosting' },
            { label: 'WordPress Hosting', url: '/wordpress-hosting' },
            { label: 'Software Licenses', url: '/software-licenses' },
          ],
        },
        {
          heading: 'COMPANY',
          links: [
            { label: 'About Us', url: '/about-us' },
            { label: 'Our Network', url: '#' },
            { label: 'Careers', url: '#' },
            { label: 'Blog', url: '/blog' },
          ],
        },
        {
          heading: 'SUPPORT',
          links: [
            { label: 'Knowledge Base', url: '/support' },
            { label: 'Network Status', url: '#' },
            { label: 'Contact Support', url: '/contact-us' },
          ],
        },
        {
          heading: 'LEGAL',
          links: [
            { label: 'Terms of Service', url: '/terms-of-service' },
            { label: 'Privacy Policy', url: '/privacy-policy' },
            { label: 'Refund Policy', url: '#' },
          ],
        },
      ],
      social: [
        { label: 'X', url: '#', icon: '' },
        { label: 'in', url: '#', icon: '' },
        { label: 'Website', url: '#', icon: 'globe' },
        { label: 'Circle', url: '#', icon: '' },
      ],
    },
  },
  {
    page: SiteContentNamespace.EPage.LEGAL,
    content: {
      termsUpdated: 'August 1, 2026',
      termsBody:
        "These Terms of Service govern your use of ZexServer's hosting, licensing and support services. By creating an account or using our services you agree to these terms.\n\n1. Accounts\nYou are responsible for maintaining the security of your account and for all activity that occurs under it.\n\n2. Acceptable Use\nServices may not be used for illegal activity, spam, malware distribution, or to disrupt other customers' services.\n\n3. Billing\nServices are billed in advance on a recurring basis. Failure to pay may result in suspension or termination of service.\n\n4. Service Availability\nWe target 99.9% uptime but do not guarantee uninterrupted service. Scheduled maintenance will be communicated in advance where possible.\n\n5. Termination\nEither party may terminate service at any time. Refunds are handled per our Refund Policy.\n\n6. Limitation of Liability\nZexServer is not liable for indirect, incidental or consequential damages arising from use of our services.",
      privacyUpdated: 'August 1, 2026',
      privacyBody:
        'This Privacy Policy explains how ZexServer collects, uses and protects your information.\n\n1. Information We Collect\nAccount details (name, email, billing address), payment information, and technical data such as IP addresses and server logs.\n\n2. How We Use Information\nTo provide and bill for services, respond to support requests, and improve our infrastructure and offerings.\n\n3. Data Sharing\nWe do not sell your personal data. Information may be shared with payment processors and infrastructure partners strictly to deliver our services.\n\n4. Data Security\nWe use industry-standard security measures including encryption in transit and access controls to protect your data.\n\n5. Data Retention\nAccount and billing data is retained for as long as your account is active, and as required by law thereafter.\n\n6. Your Rights\nYou may request access to, correction of, or deletion of your personal data at any time by contacting support.',
    },
  },
  {
    page: SiteContentNamespace.EPage.SETTINGS,
    content: { siteName: 'ZexServer', logo: '', favicon: '', shareImage: '' },
  },
];
