/** --------------------------------------------------------------------------------------------------------------------
 * @file abstract.entity.ts
 * @tutorial Only need to extend in your entity.
 * @description This class provides a base entity with an autogenerated id and timestamps.
 */
import { PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';
import { IAbstractEntity } from '../interface/abstractEntity.interface';

/** --------------------------------------------------------------------------------------------------------------------
 * @description AbstractEntity class for TypeORM
 *
 * @class AbstractEntity
 */
export abstract class AbstractEntity implements IAbstractEntity {
  @PrimaryGeneratedColumn('uuid')
  _id?: string;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt?: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt?: Date;
}
